New branch shirshov
IlyaOrlov/PythonCourse2.0_June22 pull request #10
Opened 2022-06-30 09:51 UTC by DNN0SHI

тест GIT

2022-06-30 14:50 UTC, DNN0SHI commented
for my test GIT

2022-06-30 18:36 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work2.py
> +from turtledemo.penrose import star
Оу, этот код немножко лишний, т.к. далее не используется)

2022-07-02 13:17 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work2.py
> +from turtledemo.penrose import star
а подскажите пожалуйста, разве **impotr time** при работе с временем не нужен?

2022-07-02 18:02 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work1.py
> +house = input ("Введите номер дома: ") #ввод исходных данных
Здесь и ниже: пробелов между input и скобкой быть не должно - [PEP8](https://peps.python.org/pep-0008/#:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call%3A)

2022-07-02 18:03 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_1_2.py
> +print("Новая задача")
Этот вызов print выше секции импортов не укладывается в корректную структуру кода.

2022-07-02 18:05 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_2_2.py
> +result = int(diff) /int(distance)   # расчет
Разность целых чисел - априори целое число, поэтому оборачивать diff в int излишне.

2022-07-02 18:05 UTC, IlyaOrlov requested changes
Всё хорошо, но есть небольшие замечания.

2022-07-02 18:41 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work1.py
> +house = input ("Введите номер дома: ") #ввод исходных данных
добрый вечер Илья, спасибо не заметил пробелы все исправлю

2022-07-02 18:44 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_1_2.py
> +print("Новая задача")
спасибо, тогда лучше наверное полностью убрать этот вывод?

2022-07-02 18:45 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_1_2.py
> +print("Новая задача")
наверное, да)

2022-07-02 18:48 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_2_2.py
> +result = int(diff) /int(distance)   # расчет
тогда наверное было бы правильнее исходные данные изначально задавать в int:
start = int(input("Топлива было: "))    # ввод исходных данных
end = int(input("Топлива осталось: "))  # ввод исходных данных
distance = int(input("Расстояние: "))  # ввод исходных данных

или нет?

2022-07-02 18:56 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_2_2.py
> +result = int(diff) /int(distance)   # расчет
Кстати, тоже очень хорошее решение! Пожалуй, для нашего примера оно даже логичней и проще. Единственно, если мы захотим перед приведением к целочисленному типу проверить, можно ли вообще такое приведение сделать для введенных пользователем данных (вдруг он ввел не числа, а буквы какие-нибудь), то такое решение не подойдёт. Кстати, на следующем занятии мы как раз узнаем, как сделать такую проверку.

2022-07-02 19:30 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_2_2.py
> +result = int(diff) /int(distance)   # расчет
Я  тоже об этом думал, а так же было бы логично чтобы вторая переменная  "end = int(input("Топлива осталось: ")"  всегда была бы меньше  переменной  "start".

2022-07-02 19:39 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_2_2.py
> +result = int(diff) /int(distance)   # расчет
Тоже верное замечание! Вообще, контроль действий пользователя - как предусмотреть разные варианты, которыми он может сломать программу - это большая тема для исследования.

2022-07-02 19:40 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-07-02 19:40 UTC, merged