New branch shirshov
IlyaOrlov/PythonCourse2.0_June22 pull request #21
Opened 2022-07-04 06:33 UTC by DNN0SHI

Добавлен файл с комментариями по PEP8

2022-07-04 08:17 UTC, IlyaOrlov requested changes
Всё хорошо, только пара небольших замечаний (надо поправить комментарии).

2022-07-04 08:17 UTC, IlyaOrlov commented on Practice/Shirshov_/pep8task_me_coment.py
> +          f = open(output, 'r')     # добавить пробелы (2 шт.)
В стр. 24-25 на самом деле всё непросто) Они действительно требуют выравнивания. Здесь выполняется открытие файла и запись в него содержимого контейнера self.map. Если сдвинуть строки вправо (под цикл for) - то файл будет перезаписываться многократно, при каждом добавлении элемента в self.map. А если сдвинуть влево (на один уровень с for), то в файл запишется один раз только итоговый вариант self.map.

2022-07-04 08:17 UTC, IlyaOrlov commented on Practice/Shirshov_/pep8task_me_coment.py
> +          mp3s = []  # должен быть выровнен по self.map (добавить пробелы)
В стр. 28-29 идёт работа с файлом f. Данная инструкция (здесь просто создается новый пустой список) к вышестоящему блоку никак не привязана, поэтому лучше выровнять ее по with (не внося в само тело блока with).

2022-07-04 10:55 UTC, DNN0SHI commented on Practice/Shirshov_/pep8task_me_coment.py
> +          f = open(output, 'r')     # добавить пробелы (2 шт.)
Спасибо, этого я не учел

2022-07-04 10:57 UTC, DNN0SHI commented on Practice/Shirshov_/pep8task_me_coment.py
> +          mp3s = []  # должен быть выровнен по self.map (добавить пробелы)
понял, спасибо

2022-07-04 19:45 UTC, IlyaOrlov commented on Practice/Shirshov_/pep8task_me_coment.py
> +    Shuffler = shuffler()   # необходимо изменить имя класа на соответствующее, которое задано с верху
Кстати, здесь имя класса - справа, а слева - объект этого класса. Поэтому, если исправить строку 9, то здесь правильно писать так: shuffler = Shuffler()

2022-07-04 19:45 UTC, IlyaOrlov commented on Practice/Shirshov_/pep8task_me_coment.py
> +main()  # добавить пробелы (4 шт.)
Нет-нет! Здесь всё корректно. Это как раз основной код (поэтому две пустые строки сверху нужны и пробелов добавлять не нужно), состоящий из вызова ранее определенной функции **main**.

2022-07-05 14:32 UTC, DNN0SHI commented on Practice/Shirshov_/pep8task_me_coment.py
> +    Shuffler = shuffler()   # необходимо изменить имя класа на соответствующее, которое задано с верху
спасибо исправлю

2022-07-05 14:33 UTC, DNN0SHI commented on Practice/Shirshov_/pep8task_me_coment.py
> +main()  # добавить пробелы (4 шт.)
замечания приняты в работу, спасибо

2022-07-05 15:08 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-07-05 15:08 UTC, merged