Начал делать дз №4
IlyaOrlov/PythonCourse2.0_June22 pull request #28
Opened 2022-07-05 21:41 UTC by StoyanovP

2022-07-06 06:59 UTC, IlyaOrlov requested changes
Всё супер! Добавил несколько предложений по оптимизации кода.

2022-07-06 06:59 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +    print(f"{i} цифра равна {num[x]}")
**x** тут и не особо нужен, т.к. он всегда будет равен **i - 1**, т.е. можно писать num[i - 1]

2022-07-06 06:59 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +    if word in stop_list:
Как мы узнаем на следующих занятиях, операция **in** (не путать с **in** в цикле for!) быстрее всего работает с типом множество. Поэтому stop_list лучше задать как множество:
```python
stop_list = {'stop', 'Stop', 'STOP'}
```
Казалось бы, только квадратные скобки заменили на фигурные, а скорость (особенно для большого набора данных) увеличится значительно.
Есть, правда, решение еще проще:)
```python
if word.lower() == 'stop':
```

2022-07-06 06:59 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +for i in list_phrase:
А для обхода всевозможных перечислений, которые не меняются по ходу программы, больше подойдёт тип кортеж, потому что у него все элементы хранятся рядышком, а не разбросаны по памяти. Поэтому list_phrase стоит задать как кортеж (круглые скобки):
```python
list_phrase = ("Ты сам-то понял, что написал?", "Аргументируй", "И?")
```

2022-07-06 11:03 UTC, StoyanovP commented on Practice/Stoyanov/hw4.py
> +for i in list_phrase:
Поправил

2022-07-06 18:10 UTC, IlyaOrlov requested changes
Оставил один небольшой комментарий.

2022-07-06 18:10 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +    test = word.isdigit()
Если пользователь ввёл stop, вычислять test не имеет смысла. Поэтому word.isdigit() лучше вычислять непосредственно в стр. 37.

2022-07-06 18:28 UTC, StoyanovP commented on Practice/Stoyanov/hw4.py
> +    test = word.isdigit()
elif not word.isdecimal(): так?
заменил isdigit на isdecimal потому что оно не будет воспринимать символы дробей и степеней.

2022-07-06 19:53 UTC, IlyaOrlov requested changes
Всё хорошо) Остались только замечания по игре К-Н-Б.

2022-07-06 19:53 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +    if player.lower() == "стоп":
Имеет смысл запомнить значение player.lower(), чтоб потом каждый раз эту функцию (lower) не вызывать.

2022-07-06 19:53 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +        if player.lower() == "камень" and random.choice(lst) == "ножницы":
Здесь и в стр. 92, 97 player.lower() уже не нужно перепроверять.

2022-07-06 19:53 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +    elif player.lower() == random.choice(lst):
Компьютер немного жульничает) Если здесь не ничья, то повторный вызов random.choice(lst) в стр. 87, 92, 97 приведёт к выбору им уже нового значения)
Поэтому random.choice(lst) стоит тоже вызвать один раз и сохранить в переменную.

2022-07-07 11:45 UTC, StoyanovP commented on Practice/Stoyanov/hw4.py
> +    if player.lower() == "стоп":
Поправил

2022-07-07 11:46 UTC, StoyanovP commented on Practice/Stoyanov/hw4.py
> +        if player.lower() == "камень" and random.choice(lst) == "ножницы":
Поправил

2022-07-07 11:46 UTC, StoyanovP commented on Practice/Stoyanov/hw4.py
> +    elif player.lower() == random.choice(lst):
Поправил

2022-07-07 19:37 UTC, IlyaOrlov requested changes
Всё супер! Только один небольшой комментарий оставил.

2022-07-07 19:37 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +    elif int(player) != number:
Имеет смысл запомнить int(player) в какую-нибудь переменную (где-то между строками 65 и 66), чтоб лишние разы это преобразование не выполнять.

2022-07-08 08:34 UTC, StoyanovP commented on Practice/Stoyanov/hw4.py
> +    elif int(player) != number:
Не понимаю как это сделать. Если перед циклом объявить переменную num_player = int(player) и подставить ее в код вместо int(player) то программа перестает работать корректно.

2022-07-08 11:53 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +    elif int(player) != number:
Перед циклом не надо, т.к. это до проверки (стр. 64). Лучше так:
```python
player = input("Теперь попробуй отгадать число из заданного тобой интервала: ")
while True:
    if not player.isdecimal():
        break  # если мы попадём сюда, то и так выйдем из цикла, поэтому elif далее можно не писать
    
    player = int(player)
    if player == number:
        print("Молодец! Ты угадал.")
```

2022-07-08 11:55 UTC, IlyaOrlov commented on Practice/Stoyanov/hw4.py
> +    elif int(player) != number:
И в стр. 69 можно уже на неравенство не проверять, т.к. player либо равен number, либо - нет (третьего не дано). Лучше сразу писать проверки на больше/меньше.

2022-07-08 13:18 UTC, StoyanovP commented on Practice/Stoyanov/hw4.py
> +    elif int(player) != number:
Поправил

2022-07-08 14:35 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-07-08 14:35 UTC, merged