New branch shirshov
IlyaOrlov/PythonCourse2.0_June22 pull request #31
Opened 2022-07-06 14:36 UTC by DNN0SHI

homework task 1 and 2 of lecture 3

к сожалению, остальные не успеваю доделать.

2022-07-06 18:29 UTC, IlyaOrlov requested changes
OK, но есть замечания по использованию функций.

2022-07-06 18:29 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_1.py
> +def perimeter():
Лучше передавать сюда a и b, как аргументы. Когда функция напрямую зависит от глобальных аргументов, которые могут как угодно меняться в окружающем коде, мы легко можем получить непредсказуемый результат. Так делать ни в коем случае не надо. Это же относится и к функциям файла Home_work_3_2.py

2022-07-06 18:29 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_1.py
> +    check_val(a)
Внутри этой функции тоже цикл. Лучше сделать, чтоб check_val возвращала корректное число (после всех проверок), а здесь мы могли написать a = check_val().

2022-07-07 10:10 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_1.py
> +    check_val(a)
Спасибо, исправлю

2022-07-07 10:44 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_1.py
> +        break
break тогда лишний

2022-07-07 10:44 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_1.py
> +    global flag1
всё равно глобальная переменная

2022-07-07 10:45 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_1.py
> +    while val.isdecimal() == True:
А зачем тогда этот цикл? Пусть лучше здесь пользователь вводит значения while not val.isdecimal()

2022-07-07 12:24 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_1.py
> +        break
Ок, уберу

2022-07-07 12:31 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_1.py
> +    while val.isdecimal() == True:
Это цикл используется в функции для проверки на переменную числовая или нет. Можно просто использовать while val.isdecimal(): , а если использовать while not val.isdecimal() то цикл необходимо сделать в обратном порядке и он приводит к зациклеванию.

2022-07-07 19:17 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_4.py
> +        s2 = s1.replace("a", "*")
Допустимо совместить два небольших выражения: s3 = s1.replace("a", "*").replace("A", "*")

2022-07-07 19:53 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_4.py
> +        s2 = s1.replace("a", "*")
спасибо, исправлю

2022-07-08 08:00 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_5.py
> +        if st1 == st1[::-1]:
реализовал

2022-07-08 08:00 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_5.py
> +            print(st1 == st1[::-1])
поправил

2022-07-08 11:56 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_1.py
> +    while Flag_start:
Flag_start уже и не нужен. Можно просто написать **while True:**

2022-07-08 11:57 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_1.py
> +
Что-то много пустых строк.

2022-07-08 11:57 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_2.py
> +from Home_work_3_1 import check_val
Отличное решение!

2022-07-08 11:58 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_3.py
> +while flag_sart:
Здесь flag_sart тоже не особо нужен.

2022-07-08 11:58 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_3_2.py
> +while flag_sart:
И здесь flag_sart тоже не особо нужен.

2022-07-08 12:02 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_4_1.py
> +    if st % 3 == 0:
Если число кратно 15 (а значит и 3, и 5), то для него выполнятся стр.13, 15 и 17, хотя достаточно только  стр. 17. Поэтому лучше проверку на кратность 15 выполнить первой, а остальные условия записать через elif.

2022-07-08 12:03 UTC, IlyaOrlov requested changes
Стало гораздо лучше! Но есть ещё несколько моментов, которые можно оптимизировать.

2022-07-08 19:55 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_1.py
> +    while Flag_start:
спасибо, не знал исправлю

2022-07-08 19:57 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_1.py
> +
исправлю

2022-07-09 13:08 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_3.py
> +while flag_sart:
исправлю

2022-07-09 13:09 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_3_3_2.py
> +while flag_sart:
исправлю

2022-07-09 13:15 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_4_1.py
> +    if st % 3 == 0:
подскажи те пожалуйста вы имеете ввиду так:
for i in range(1, n+1):
    st = i
    if st % 15 == 0:
        i = 'FizzBuzz'
    elif st % 5 == 0:
        i = 'Buzz'
    elif st % 3 == 0:
        i = 'Fizz'
    print(i)

2022-07-11 08:34 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_1.py
> +            True
Это True здесь лишнее. Условие цикла задано в стр. 9, выход из цикла выполняется через return по условию в стр. 11

2022-07-11 08:34 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_3.py
> +        True
Это True здесь лишнее. Условие цикла задано в стр. 11, выход из цикла выполняется через break по условию в стр. 13

2022-07-11 08:34 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_3_2.py
> +        True
Это True здесь лишнее.

2022-07-11 08:34 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_4.py
> +while True:
А вот здесь получился бесконечный цикл! Надо как-то реализовать условие выхода.

2022-07-11 08:34 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_3_5.py
> +while True:
Здесь тоже получается бесконечный цикл. Строки 16, 20 и 23 ничего не делают. Если мы ждём именно ввода палиндрома, то ситуацию можно исправить, заменив стр.16 на break

2022-07-11 08:34 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_4_1.py
> +    if st % 3 == 0:
Да, только st не нужна. Всё то же можно делать и с i.

2022-07-11 08:43 UTC, IlyaOrlov requested changes
Оставил несколько замечаний.

2022-07-11 08:43 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_4_2.py
> +
Хорошо бы ещё добавить сюда проверку на пятизначность.

2022-07-11 08:43 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_4_3.py
> +        True
Это True здесь лишнее.

2022-07-11 08:43 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_4_3.py
> +        res = res.__add__(n)
Вызовы методов, названия которых начинаются с двойного нижнего подчеркивания, в большинстве случаев являются нежелательными. Вместо них всегда можно вызвать обычные операторы. Например, в данном случае можно просто написать res = res + n или res += n.

2022-07-11 08:43 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_4_4.py
> +        True
Это True здесь лишнее.

2022-07-11 09:14 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_4_1.py
> +    if st % 3 == 0:
спасибо, исправлю

2022-07-11 12:52 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_4_2.py
> +
Да конечно можно, но тогда программа теряет универсальность

2022-07-11 13:14 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_4_2.py
> +
Хороший аргумент) но у вас и так в приглашении ко вводу требуется именно "пятизначное" число.
Можно задать количество цифр константой: NUM_LEN = 5 и далее в коде (и даже в приглашении ко вводу) везде использовать NUM_LEN. Тогда при необходимости поменять длину достаточно будет сделать изменение в одном месте.
На практике такой контроль длины может применяться, например, в система аутентификации со вводом пароля (там длина пароля может прописываться такой же константой или в конфигурационных файлах).

2022-07-11 19:19 UTC, IlyaOrlov requested changes
Все замечания исправлены. Остался только один вопрос!

2022-07-11 19:19 UTC, IlyaOrlov commented on Practice/Shirshov_/Home_work_4_8.py
> +        if result(user) == result(comp):
Вообще, это хорошая идея использовать именно числа для кодирования вариантов (т.к. они сравниваются в разы быстрее, чем строки), но почему здесь мы сравниваем не comp и user, а то, что возвращает result (т.е. строки)?

2022-07-13 06:22 UTC, DNN0SHI commented on Practice/Shirshov_/Home_work_4_8.py
> +        if result(user) == result(comp):
Спасибо, действительно это будет  работать быстрее и так более логично

2022-07-13 18:27 UTC, IlyaOrlov approved these changes
Теперь всё отлично!!!

2022-07-13 18:27 UTC, merged