ulia sherbakova
IlyaOrlov/PythonCourse2.0_June22 pull request #38
Opened 2022-07-08 17:26 UTC by uliasherb

Мое домашнее задание 4.3

2022-07-08 19:57 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz4.3.py
> +while (s := input("Введите символ: ")) != 'stop' and s != 'Stop' and s!= 'STOP':
Можно попроще: применить lower() и сравнить только со stop.

2022-07-08 19:58 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz4.3.py
> +       print("Я просил число, попробуй снова")
Справедливости ради: в стр. 1 просили ввести символ, а не число:)

2022-07-08 19:59 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz4.4.py
> +      i += 1
А что будет, когда i станет больше 2?

2022-07-08 20:00 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz4.6.py
> +def fun2(c, d):
Вопрос на понимание: что вернет функция, если c и d равны?

2022-07-09 10:30 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz4.6.py
> +    return (max(c,d))
Можно и без скобок вокруг max. Да и первоначальный вариант без max был хорош.

2022-07-09 21:04 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz4.5.py
> +random = random.randint(beg, end)
Не стоит использовать для именования переменных названия стандартных модулей или функций. Это приведёт к тому, что оригинальный модуль (random) будет недоступен.

2022-07-09 21:04 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz4.5.py
> +    if int(s) > random:
Лучше перед 10-й строкой один раз привести s к типу int, чтоб потом не повторять эту операцию.

2022-07-09 21:04 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz4.4.py
> +      i += 1
Надо либо обнулять i (начиная обход списка сначала), либо вытаскивать элементы из списка через random.choice

2022-07-09 21:04 UTC, IlyaOrlov requested changes
Добавил несколько замечаний.

2022-07-10 19:18 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz4.4.py
> +      if i > 2:
Можно еще немного оптимизировать код в стр. 5 - 7 (чтоб лишний раз i не плюсовать):
```
if i < 2:
    i += 1
else:
    i = 0
```

2022-07-11 08:19 UTC, IlyaOrlov requested changes
С новыми заданиями - всё ОК. Остались только вопросы по старым заданиям.

2022-07-11 08:41 UTC, uliasherb commented
> С новыми заданиями - всё ОК. Остались только вопросы по старым заданиям.

Вроде на все ответила..

2022-07-11 10:01 UTC, IlyaOrlov commented
> 
Остался вопрос к dz4.6.py и по break в dz4.5.py

2022-07-11 12:25 UTC, uliasherb reviewed
тест

2022-07-11 12:27 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz4.6.py
> +def fun2(c, d):
убрала break

2022-07-11 12:32 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-07-11 12:32 UTC, merged