ulia sherbakova
IlyaOrlov/PythonCourse2.0_June22 pull request #43
Opened 2022-07-14 14:03 UTC by uliasherb

Мое домашнее задание 6.1

2022-07-14 21:37 UTC, Kate-Shipunova commented on Practice/Ulia Sherbakova/dz6.1.py
> +print(f"Модель 1 танка: {e1.model}, его мощность {e1.power}, его скорость {e1.speed}")
Можно задать метод в родительском классе, например show_tank(self)(название на ваше усмотрение) и перенести туда 
"print(f"Модель 1 танка: {self.model}, его мощность {self.power}, его скорость {self.speed}")"

а здесь вызвать этот метод. За одно и наследование в действие проверим.

2022-07-14 21:37 UTC, Kate-Shipunova commented on Practice/Ulia Sherbakova/dz6.2.py
> +    def __lt__(self, other):
Сейчас у нас метод работает некорректно, т.к. при вызове
print(f"Тяжелее утка {e2 > e1}")   #  получим "Тяжелее утка Малышка"
Для корректной работы метода нам будет достаточно сохранить результат сравнения "self.weight < other.weight" в переменную, и если значение нашей переменной True - значит вес экземпляра до "<" меньше веса экземпляра после "<" -> будем возвращать имя other.
Если же переменная будет False, значит имя self.
При этом интерпритатор достаточно умен, чтобы возвращать корректное имя тяжелой утки не только, когда мы используем оператор "<"(за ним кроется __lt__) 
print(f"Тяжелее утка {e2 < e1}")
print(f"Тяжелее утка {e1 < e2}")
но и при использовании оператора  ">"(за ним кроется __gt__), хотя мы его в нашем классе и не задаем:
print(f"Тяжелее утка {e2 > e1}")
print(f"Тяжелее утка {e1 > e2}")

2022-07-17 09:03 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz6.1.py
> +print(f"Модель 1 танка: {e1.model}, его мощность {e1.power}, его скорость {e1.speed}")
поправила

2022-07-17 09:03 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz5.2.py
> +    uniq = []
поправила

2022-07-17 09:22 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz6.2.py
> +    def __lt__(self, other):
поправила

2022-07-17 16:35 UTC, Kate-Shipunova approved these changes

2022-07-17 18:24 UTC, IlyaOrlov requested changes
Всё супер! Остались небольшие замечания по dz5.5.py

2022-07-17 18:24 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz5.5.py
> +f.close()
Когда мы работаем с файлом через with, файл закроется сам, и close() вызывать уже не нужно. With для того и нужен, чтоб занятый ресурс (в данном случае файл) освобождался автоматически.

2022-07-17 18:24 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz5.5.py
> +            print(i.replace("\n", "    "))
Только табуляция - это не \n, а \t. Чтоб при выводе на экран строку с табуляцией можно было визуально отличить от пробелов, можно использовать функцию repr: 
```python
s = "New\tYear"
print(repr(s))
```
Ну и лучше записывать измененные строки в новый файл, а не просто выводить на экран.

2022-07-18 09:01 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz5.5.py
> +            print(i.replace("\n", "    "))
поправила

2022-07-18 09:02 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz5.5.py
> +f.close()
поправила

2022-07-18 19:00 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz5.4.py
> +def fun(arr):
Отступы великоваты. Таков побочный эффект использования табуляции вместо 4-х пробелов)

2022-07-18 19:04 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz5.4.py
> +arr = ([arr1, arr2, arr3])
А вот для такого примера не сработает:
```python
arr1 = [20, 20, 20]
arr2 = [18, 21, 18]
arr3 = [21, 20, 19]
```
Кстати, можно матрицу задавать просто как список списков:
```python
arr = [
    [20, 20, 20],
    [18, 21, 18],
    [21, 20, 19]
]
```

2022-07-18 22:33 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz5.5.py
> +f2 = open("2.txt", "w")
внесла правки

2022-07-19 10:23 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz5.4.py
> +arr = [[20, 20, 20],
А для такого примера сработает (удаляем 20)?
```python
arr = [
       [1, 20, 20],
       [18, 21, 18],
       [21, 20, 19]
]
```
Наверное, count1 и count2 стоит увеличивать вместе с i и j.
Вообще, я бы сначала собрал элементы для номера столбцов для удаления в отдельный контейнер. А потом уже за ещё один проход удалил бы их. Иначе получается, что проходя по матрице и тут же удаляя элементы, мы как бы рубим сук, на котором сидим

2022-07-19 14:53 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz7.1.py
> +    def solve_task(self):
поправила

2022-07-19 14:58 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz7.2.py
> +    s = random.randint(3, 6)
поправила

2022-07-19 19:28 UTC, IlyaOrlov requested changes
Остались замечания по dz5.4.py

2022-07-19 19:28 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz5.4.py
> +                    del(arr[count1][count2])
Тогда уж надо во всех строках эту колонку удалять, иначе будут пропущенные столбцы. Например, для исходной матрицы:
```python
arr = [
    [20, 20, 20],
    [18, 21, 18],
    [21, 20, 19]
]
```
результат получается очень странный.

2022-07-19 19:28 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz5.4.py
> +    a = 20
**a** лучше тоже сделать аргументом функции. Иначе получается, что данная функция специализируется именно на удалении элемента со значением 20. Слишком узкая специализация)

2022-07-20 09:13 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz5.4.py
> +    a = 20
сделала

2022-07-20 09:15 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz5.4.py
> +                    del(arr[count1][count2])
внесла правки, наконец-то результат корректный!)

2022-07-20 18:25 UTC, Kate-Shipunova approved these changes

2022-07-20 19:43 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz5.4.py
> +        for row in arr:
Сейчас, конечно, код работает корректно. Но копировать весь столбец в отдельный список только ради того, чтоб узнать, есть ли в столбце искомый элемент, это как-то неэффективно. Ведь нам достаточно в этом цикле проверить равен ли какой-то из row[count2] искомому значению **a**, или нет.

2022-07-21 12:50 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz5.4.py
> +        for row in arr:
поправили

2022-07-21 16:16 UTC, IlyaOrlov approved these changes
По заданиям базовой части курса всё отлично!

2022-07-21 16:18 UTC, merged