Stoyanov
IlyaOrlov/PythonCourse2.0_June22 pull request #47
Opened 2022-07-19 18:02 UTC by StoyanovP

Начал делать дз №5

2022-07-19 19:05 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_5.py
> +    for k in dictionary.keys():
Зависимость функции от глобальных переменных снижает гибкость и универсальность кода (это как зависимость от импортных запчастей в отечественных автомобилях): dictionary стоит тоже передавать в функцию в качестве параметра.

2022-07-19 19:11 UTC, IlyaOrlov requested changes
Всё хорошо. Оставил несколько замечаний.

2022-07-19 19:11 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_5.py
> +    for j in arr[k + 1: len(arr)]:
len(arr) можно не писать: for j in arr[k + 1:] - всё равно будет срез до конца arr.

2022-07-19 19:11 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_5.py
> +    y = arr.index(min_, x, len(arr))
ОК. Но нужно понимать, что index снова пойдет по списку (хоть и не по всему) в поисках индекса ранее найденного минимального элемента. А ведь можно сразу вместе с min_ запомнить и индекс этого минимума.

2022-07-19 19:52 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +    for k in dictionary.keys():
Поправил

2022-07-19 19:52 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +    for i in lst:
Поправил

2022-07-19 19:52 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +    for j in arr[k + 1: len(arr)]:
Точно, забыл что по умолчанию срез будет идти до конца

2022-07-19 19:52 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +    y = arr.index(min_, x, len(arr))
Пока не вспомнил про то что у index можно задавать интервал поиска, была проблема связанная именно с тем, что возвращался индекс первого из повторяющихся элементов (даже хотел уже отправлять решение с пометкой только для списков без повторяющихся элементов)
Не приходит в голову как получить индекс в момент получения min_

2022-07-20 20:28 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_5.py
> +    y = arr.index(min_, x, len(arr))
Надо вместе с проходом по подсписку запоминать индексы элементов. Например, так:
```python
min_ = i
index_min_ = k
index_ = k + 1
for j in arr[k + 1:]:
    if j <= min_:
        min_ = j
        index_min_ = index_
    index_ += 1  
```
Решение получится чуть посложнее, но зато гораздо эффективней. А код поиска индекса минимального элемента можно вообще в отдельную функцию вынести.

2022-07-20 20:36 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_5.py
> +    for n, x in enumerate(matrix):
Какой смысл n?
Также, удаляя элементы по данному алгоритму, мы можем пропускать столбцы.
Например, в матрице:
```python
matrix = [
    [1, 1],
    [2, 2]
]
```
удаляем столбцы с элементом 1. Должен остаться список из пустых списков...

2022-07-20 20:38 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_5.py
> +def write(new_file):
Алгоритм хорош, только определение функции стоит поднять выше основного кода (стр. 81-85).

2022-07-21 13:32 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +def write(new_file):
Поправил

2022-07-21 13:32 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +    for n, x in enumerate(matrix):
n была потому что не подумал что можно обратиться по индексу)
Доработал, теперь удаляет все столбцы с заданной цыфрой

2022-07-21 13:32 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +print(f"{matrix[0]}\n{matrix[1]}\n{matrix[2]}")
Исправил

2022-07-21 13:32 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +    y = arr.index(min_, x, len(arr))
Исправил

2022-07-21 16:03 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_5.py
> +    y = arr.index(min_, x, len(arr))
Хорошо. Только лучше, чтоб функция возвращала index_min_ через return, а не использовала глобальную переменную. Зависимости от глобальных переменных всегда лучше избегать.

2022-07-21 16:12 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_5.py
> +    for x in enumerate(matrix):
enumerate не нужен. Можно просто for x in matrix и работать с **x**.

2022-07-21 16:17 UTC, IlyaOrlov requested changes
ОК. Осталась пара небольших замечанийЁ

2022-07-21 16:21 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +    y = arr.index(min_, x, len(arr))
Исправил

2022-07-21 16:23 UTC, IlyaOrlov requested changes

2022-07-21 16:23 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_5.py
> +    arr[x], arr[index_min(k, min_)] = arr[index_min(k, min_)], arr[x]
Не надо два раза вызывать функцию с одними и теми же аргументами! Надо сохранить результат первого вызова в переменную и использовать эту переменную. Иначе - лишняя работа!

2022-07-21 16:29 UTC, StoyanovP commented on Practice/Stoyanov/hw_5.py
> +    arr[x], arr[index_min(k, min_)] = arr[index_min(k, min_)], arr[x]
Исправил

2022-07-21 16:34 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-07-21 16:34 UTC, merged