Chertova branch
IlyaOrlov/PythonCourse2.0_June22 pull request #48
Opened 2022-07-20 14:23 UTC by AChertova

Задание  6_3

2022-07-23 08:36 UTC, IlyaOrlov commented on Practice/achertova/Rabota8_1Paragraph.py
> +	def __init__(self, str):
Не стоит использовать названия стандартных функций (речь о str) для именования своих переменных.

2022-07-23 08:39 UTC, AChertova commented on Practice/achertova/Rabota8_1Paragraph.py
> +	def __init__(self, str):
Исправила

2022-07-23 08:44 UTC, IlyaOrlov commented on Practice/achertova/Rabota8_1Paragraph.py
> +				self.i += 1
Логика использования итератора абсолютно правильная! Только чтоб потом (в стр. 15 не делать срез) здесь вместе с инкрементом self.i можно заодно и добавлять элементы в **a**: a += s[self.i]
Тогда в ветке else останется всего две операции.

2022-07-29 10:43 UTC, AChertova commented on Practice/achertova/Rabota10_1Walrus.py
> +lst2 = []
Когда писала, почему-то не получалось. Сейчас получилось, поправила

2022-07-29 10:47 UTC, AChertova commented on Practice/achertova/Rabota8_1Paragraph.py
> +		self.s = s
Поправила

2022-07-29 11:23 UTC, AChertova commented on Practice/achertova/Rabota8_4Itertools.py
> +it2 = itertools.filterfalse(lambda _: len(_) < 5, l2)
Ок, исправила

2022-07-29 11:25 UTC, AChertova commented on Practice/achertova/Rabota8_4Itertools.py
> +# Пыталась применить dropwhile вместо ilterfalse, но выдавал всю последовательность,
Все поняла, спасибо!

2022-07-30 17:27 UTC, IlyaOrlov commented on Practice/achertova/Rabota8_1Paragraph.py
> +				self.i += 1
Да, теперь почти всё правильно. **a** обнуляется в стр.12 при очередном вызове next. И это правильно, т.к. **a** - это буфер для содержимого очередного параграфа.
Непонятно, почему итератор работает с глобальной переменной **s**, хотя у него есть свой атрибут self.text. Зависимость от глобальных переменных - это всегда плохо, т.к. снижает гибкость отдельных программных объектов (функций, классов).

2022-08-01 11:03 UTC, IlyaOrlov requested changes
Оставил несколько существенных замечаний.

2022-08-01 11:03 UTC, IlyaOrlov commented on Practice/achertova/Rabota9_2WorkingTime.py
> +	if first_day == "Saturday":
Лучше проверять first_day и last_day в их численном представлении. Сравнение чисел в разы быстрее, чем сравнение строк.

2022-08-01 11:03 UTC, IlyaOrlov commented on Practice/achertova/Rabota9_4HumanDs.py
> +		print(h.__dict__)
Обращаться к приватному атрибуту, нарушая инкапсуляцию, нехорошо. Надо реализовать у Human метод ```__repr__```.

2022-08-02 06:55 UTC, AChertova commented on Practice/achertova/Rabota6_3Wrap.py
> +            return print(f"File doesn't exist")
Без return надо. Пытается сохранить для кого-то print

2022-08-02 07:11 UTC, IlyaOrlov commented on Practice/achertova/Rabota6_3Wrap.py
> +            return print(f"File doesn't exist")
ОК. Можно и print, и return. Только в одном выражении их совмещать не стоит. Я бы явно здесь прописал return None.
```python
        except FileNotFoundError:
            print(f"File doesn't exist")
            return None
        else:
            return self._content
```

2022-08-02 07:54 UTC, AChertova commented on Practice/achertova/Rabota6_3Wrap.py
> +            self._content = f.write(value)
Исправлено

2022-08-02 08:37 UTC, AChertova commented on Practice/achertova/Rabota9_1RE.py
> +		res = re.findall(("\"git .*\""), line)
Готово

2022-08-02 09:09 UTC, IlyaOrlov requested changes
Хорошо, но кое-какие замечания остались.

2022-08-02 09:09 UTC, IlyaOrlov commented on Practice/achertova/Rabota9_4HumanS.py
> +			print(h.__dict__)
Здесь тоже осталось прямое обращение к приватному атрибуту.

2022-08-02 09:11 UTC, IlyaOrlov commented on Practice/achertova/Rabota7_3Bankomat.py
> +		CashMachine.give_out_cash(self, goc)
К методу родительского класса лучше обращаться через super()

2022-08-02 09:11 UTC, IlyaOrlov commented on Practice/achertova/Rabota7_3Bankomat.py
> +		self.sumin = s
sumin - прямо напрашивается в protected атрибуты

2022-08-02 13:52 UTC, AChertova commented on Practice/achertova/Rabota9_2WorkingTime.py
> +	if first_day == "Saturday":
Сделано

2022-08-02 15:25 UTC, AChertova commented on Practice/achertova/Rabota9_4HumanDs.py
> +		print(h.__dict__)
Сделано

2022-08-02 15:25 UTC, AChertova commented on Practice/achertova/Rabota9_4HumanS.py
> +			print(h.__dict__)
Сделано

2022-08-02 15:37 UTC, AChertova commented on Practice/achertova/Rabota8_1Paragraph.py
> +				self.i += 1
А это просто объясняется. У меня были переменные названы буквами, Екатерина указала, что переменные надо обозначать более понятно, и в процессе обозначений эту s я потеряла и не поменяла. Поправила

2022-08-02 15:40 UTC, AChertova commented on Practice/achertova/Rabota8_1Paragraph.py
> +				self.i += 1
Про **a** поняла, не учла, что в next мы заново заходим каждый раз

2022-08-03 08:17 UTC, AChertova commented on Practice/achertova/Rabota7_3Bankomat.py
> +		CashMachine.give_out_cash(self, goc)
Поправила

2022-08-03 08:17 UTC, AChertova commented on Practice/achertova/Rabota7_3Bankomat.py
> +		self.sumin = s
Сделала

2022-08-03 08:31 UTC, IlyaOrlov commented on Practice/achertova/Rabota7_3Bankomat.py
> +		super(CashMachineOnline, self)._sumin(self, goc)
Наверное, здесь ожидалось обращение к сеттеру: super(CashMachineOnline, self).sumin = goc
Нет?

2022-08-03 08:36 UTC, AChertova commented on Practice/achertova/Rabota7_3Bankomat.py
> +		super(CashMachineOnline, self)._sumin(self, goc)
Да, без подчеркивания. А почему = goc? А не в аргументах?

2022-08-03 08:38 UTC, IlyaOrlov commented on Practice/achertova/Rabota7_3Bankomat.py
> +		print(super().__repr__())
Зачем print в магическом методе, который сам используется, в основном, в других принтах? Если предполагается, что наследник дополняет родителя, можно было это так и прописать: return super().__repr__() + " Перевод средств онлайн."

2022-08-03 08:38 UTC, IlyaOrlov commented on Practice/achertova/Rabota9_2WorkingTime.py
> +	if first_day == "Saturday":
Да, только преобразовывать сначала в строку, потом в число.. как-то сложно. Можно проще: first_day.weekday()

2022-08-03 08:39 UTC, IlyaOrlov requested changes
ОК. Еще несколько небольших замечаний.

2022-08-03 08:41 UTC, IlyaOrlov commented on Practice/achertova/Rabota7_3Bankomat.py
> +		super(CashMachineOnline, self)._sumin(self, goc)
property (в данном случае sumin.setter) позволяет работать именно таким способом. Это вроде как проще, нет?)

2022-08-03 09:41 UTC, AChertova commented on Practice/achertova/Rabota7_3Bankomat.py
> +		print(super().__repr__())
Задавала вопрос на лекции, предложили такой вариант наследования repr. Поправила

2022-08-03 09:41 UTC, AChertova commented on Practice/achertova/Rabota7_3Bankomat.py
> +		super(CashMachineOnline, self)._sumin(self, goc)
Сделано

2022-08-03 09:48 UTC, AChertova commented on Practice/achertova/Rabota9_2WorkingTime.py
> +	if first_day == "Saturday":
И правда. Сделано

2022-08-03 10:16 UTC, IlyaOrlov commented on Practice/achertova/Rabota7_3Bankomat.py
> +		print(super().__repr__())
Вариант неплохой. Меня именно print внутри repr насторожил)

2022-08-03 10:17 UTC, IlyaOrlov approved these changes
Теперь всё ОТЛИЧНО!

2022-08-03 10:18 UTC, merged