Alexey kharitonov
IlyaOrlov/PythonCourse2.0_June22 pull request #5
Opened 2022-06-29 17:43 UTC by onix125

2022-06-29 18:55 UTC, IlyaOrlov requested changes

2022-06-29 18:55 UTC, IlyaOrlov commented on Practice/Kharitonov/Project1.py
> +print("Echo:", str(a), b)
Отлично! Попробуйте еще через форматную строку!

2022-06-29 21:19 UTC, IlyaOrlov commented on Practice/Kharitonov/Practice 2 30.06.22
> +1.Расположить инструкции программы для вычисления площади круга в правильном порядке
Здесь лучше именно файлы с расширением .py выкладывать.

2022-06-29 21:19 UTC, onix125 commented on Practice/Kharitonov/Project1.py
> +print("Echo:", str(a), b)
city = input("Ввeдите город проживания : ")
number = input("Ввeдите номер дома : ")
print("Echo: ", str(city), number)

2022-06-30 14:16 UTC, onix125 commented on Practice/Kharitonov/Project1.py
> +print("Echo:", str(a), b)
Ок. Я потом вспомнил когда домой ехал. Ок. сделаю.

2022-06-30 18:20 UTC, onix125 commented on Practice/Kharitonov/Project1.py
> +print("Echo:", str(a), b)
Все исправил.

2022-06-30 18:32 UTC, IlyaOrlov requested changes
Всё ОК, только несколько замечаний и "Practice fixed.py" надо тоже в свою папку перенести.

2022-06-30 21:06 UTC, IlyaOrlov commented on Practice/Practice fixed.py
> +result = (float(diff) * float(distance))/100
С формулой теперь всё хорошо. Чтоб стало идеально, можно diff во float не оборачивать (он и так будет float, потому что в строке 40 получился из уменьшаемого и вычитаемого, у которых тип float). Да и в скобки произведение брать необязательно (чем меньше лишних символов - тем чище код).

2022-07-01 18:48 UTC, onix125 commented on Practice/Practice fixed.py
> +result = (float(diff) * float(distance))/100
Поправил. 
У меня вопрос если я ставлю дробное число через точку скрипт работает, а через запятую все ломается. Это нормально? Или есть оператор который будет понимать?

2022-07-01 20:00 UTC, IlyaOrlov commented on Practice/Practice fixed.py
> +result = (float(diff) * float(distance))/100
Да, нормально, потому что в python именно точка считается разделителем целой и дробной части. Встроенных операторов, которые могут интерпретировать именно запятую, как разделитель, нет. Но вы легко сможете написать свою такую функцию уже на следующем занятии)

2022-07-01 20:03 UTC, onix125 commented on Practice/Practice fixed.py
> +result = (float(diff) * float(distance))/100
Спасибо.

2022-07-01 20:07 UTC, IlyaOrlov commented on Practice/Practice fixed.py
> +  def square(r):
Если выровнять строки 19 и 21 по левому краю (без пробелов), то всё будет хорошо)  Ну и если рассуждать логически... отступы признак вложенности. Вот строка 22 вложена в функцию square - тут отступ нужен, а сама функция ни во что не вложена. Так же, как и инструкция import.
А к тому, что пишет pycharm, стоит присмотреться внимательнее.

2022-07-01 20:10 UTC, IlyaOrlov commented on Practice/Kharitonov/Practice_3_project.py
> +print(f"Маскирование : {text.replace('А', '*').replace('а', '*').replace('A', '*').replace('a', '*')}")
То, что вы предусмотрели подмену и большой А и маленькой, понятно. Но зачем дважды такую подмену повторять?

2022-07-02 05:49 UTC, onix125 commented on Practice/Kharitonov/Practice_3_project.py
> +print(f"Маскирование : {text.replace('А', '*').replace('а', '*').replace('A', '*').replace('a', '*')}")
Что бы делал подмену на ENG, Cancel->C*ncel.

2022-07-02 09:13 UTC, IlyaOrlov commented on Practice/Kharitonov/Practice_3_project.py
> +print(f"Маскирование : {text.replace('А', '*').replace('а', '*').replace('A', '*').replace('a', '*')}")
А, там и русские, и английские буквы... Тогда ОК, вопросов нет)

2022-07-02 09:16 UTC, IlyaOrlov requested changes
Всё хорошо. Замечания остались только по отступам в Practice fixed.py

2022-07-04 06:15 UTC, onix125 commented on Practice/Practice fixed.py
> +  def square(r):
Поправил.

2022-07-04 11:19 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-07-04 11:19 UTC, merged

2022-07-04 11:19 UTC, onix125 commented on Practice/Kharitonov/Practice_fixed.py
> +return math.pi * r ** 2
Не все понятно, но поправил 22 строку.

2022-07-04 11:26 UTC, onix125 commented on Practice/Kharitonov/Practice_fixed.py
> +return math.pi * r ** 2
Пока еще не разобрался с PEP