Stoyanov
IlyaOrlov/PythonCourse2.0_June22 pull request #50
Opened 2022-07-21 20:16 UTC by StoyanovP

Выполнил 7.3

2022-07-23 08:33 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +    text = f.read().split("\n")
Тут мы сразу считываем весь текст из файла, преобразуем его в список и идем по списку. Если файл очень большой, то нам не хватит памяти, чтоб выполнить эти операции. Теряется смысл итератора. Надо посимвольно считывать содержимое файла (read(1)) в какую-нибудь буферную переменную, пока не встретится символ параграфа, и потом возвращать каждый раз именно эту буферную переменную.

2022-07-30 18:07 UTC, IlyaOrlov requested changes
Хорошо. Оставил некоторые замечания/рекомендации.

2022-07-30 18:07 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +        for line in f.readlines():
f.readlines() сразу формирует список из считанных строк, и мы идём по этому списку. Неэффективно. Лучше просто: for line in f.

2022-07-30 18:07 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +# итератор сделать пока не получилось, но мысли вот такие
Близко. Только читать и проверять надо посимвольно: i = f.read(1). Символ параграфа необязательно '\n'. И указанный цикл надо как раз в next поместить.

2022-07-30 18:07 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_6.py
> +                self._content = f.read()
А нужен ли вообще self._content здесь и в стр. 111?

2022-08-09 13:50 UTC, StoyanovP commented on Practice/Stoyanov/hw_6.py
> +                self._content = f.read()
Поправил

2022-08-09 13:50 UTC, StoyanovP commented on Practice/Stoyanov/hw_8.py
> +# итератор сделать пока не получилось, но мысли вот такие
Не получилось придумать как сделать

2022-08-09 13:50 UTC, StoyanovP commented on Practice/Stoyanov/hw_8.py
> +        for line in f.readlines():
Поправил

2022-08-10 06:59 UTC, IlyaOrlov requested changes
Всё ОК. Надо доразбираться с итератором.

2022-08-10 06:59 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +# итератор сделать пока не получилось, но мысли вот такие
Подсказка. Метод ```__next__``` итератора должен получиться таким:
```python
    def __next__(self):
        buffer = ""
        while s := self._f.read(1):
            if s == self._p:
                return buffer
            else:
                buffer += s

        if buffer:
            return buffer
        
        raise StopIteration
```

2022-08-10 08:19 UTC, StoyanovP commented on Practice/Stoyanov/hw_8.py
> +# итератор сделать пока не получилось, но мысли вот такие
Вроде получилось, а без использования классов можно было решить эту задачу?

2022-08-10 08:26 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +# итератор сделать пока не получилось, но мысли вот такие
Можно было и через генератор сделать, но по заданию требуется именно итератор.

2022-08-10 08:30 UTC, StoyanovP commented on Practice/Stoyanov/hw_8.py
> +# итератор сделать пока не получилось, но мысли вот такие
Хорошо

2022-08-10 08:30 UTC, IlyaOrlov requested changes
Есть еще замечания!

2022-08-10 08:30 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +        self.f_name = file_name
Зачем хранить имя файла?

2022-08-10 08:30 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +        self._f = open(self.f_name, "r", encoding="UTF-8")
Файл где-то нужно закрыть! Лучше это сделать в методе ```__del__```, который всегда автоматически вызывается при удалении экземпляра класса (например, когда его счетчик ссылок становится равным нулю). Таким образом, мы точно не забудем освободить ресурс.

2022-08-10 08:30 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +print(next(i))
То, что next можно использовать с итераторами и генераторами, не означает, что это единственный и самый удобный способ для работы с ними. Здесь лучше подойдет старый добрый цикл for.

2022-08-10 08:44 UTC, StoyanovP commented on Practice/Stoyanov/hw_8.py
> +        self.f_name = file_name
Не совсем понял.
Я хотел чтобы можно было указать какой файл читать и до какого символа, поэтому при создании экземпляра передавал имя файла и символ.

2022-08-10 08:44 UTC, StoyanovP commented on Practice/Stoyanov/hw_8.py
> +print(next(i))
я знаю) просто не было цели вывести на экран всё.

2022-08-10 08:47 UTC, StoyanovP commented on Practice/Stoyanov/hw_8.py
> +        self.f_name = file_name
ааа понял)
    def __init__(self, file_name, paragraph):
        self._f = open(file_name, "r", encoding="UTF-8")

2022-08-10 08:51 UTC, StoyanovP commented on Practice/Stoyanov/hw_8.py
> +        self._f = open(self.f_name, "r", encoding="UTF-8")
Исправил

2022-08-10 09:28 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +        self.f_name = file_name
Да, именно это я и имел в виду)

2022-08-10 09:30 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +        self._f = open(self.f_name, "r", encoding="UTF-8")
ОК. Подробней про этот фокус с обязательным освобождением ресурса можно прочитать, погуглив про идиому RAII.

2022-08-10 09:30 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_8.py
> +print(next(i))
OK)

2022-08-10 09:30 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-08-10 09:30 UTC, merged