homework 9_1,2 from lectures 9
IlyaOrlov/PythonCourse2.0_June22 pull request #53
Opened 2022-07-26 14:27 UTC by DNN0SHI

Домашняя работа, практика по лекции 9 задание 1,2

2022-07-27 10:34 UTC, Kate-Shipunova commented on Practice/Shirshov_/H_W_9/Home_work_9_1.py
> +    res = re.findall(r'git [^а-яА-Я)"]+', i, re.M | re.U)
У нас в пункте 2 ф-ла встречаются 2 команды гит: "git clone https://github.com/IlyaOrlov/PythonCourse2.0_June22.git" и "git clone git@github.com:IlyaOrlov/PythonCourse2.0_June22.git", но с помощью указанного паттерна 2я команда возвращается в виде:
'git clone git@github.com:IlyaOrlov/PythonCourse2.0_June22.git - ', " - " явно лишние и гит на данную команду явно выругается.
Попробуйте сохранить все найденные команды в некий список, а потом повторно обработать с помощью re, чтобы убрать " - " в обсуждаемой команде.
Или просто отдельно поработайте с этой командой, чтобы сделать ее рабочей.

2022-07-27 10:34 UTC, Kate-Shipunova commented on Practice/Shirshov_/H_W_9/Home_work_9_1.py
> +for i in FileIter('../../README.md'):
Мы можем оптимизировать код, вспомнив про ф-цию re.compile(...)

2022-07-30 18:01 UTC, IlyaOrlov requested changes
Всё хорошо. Есть небольшие предложения по оптимизации и старые замечания.

2022-07-30 18:01 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_9/Home_work_9_3.py
> +        for filename in filenames:
Учитывая, что файлы должны жить меньше, лучше сначала удалять их. Иначе получится, что файлы проживут гораздо дольше отведенного им времени.

2022-08-02 14:25 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_9/Home_work_9_1.py
> +for i in FileIter('../../README.md'):
Добрый день, никак не получается вставить туда функцию re.compile(...), для оптимизации можно использовать ../*2

2022-08-02 14:36 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_9/Home_work_9_1.py
> +for i in FileIter('../../README.md'):
for i in FileIter('../'*2 + 'README.md'):

2022-08-02 19:33 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_9/Home_work_9_1.py
> +        self.file.close()
Спасибо, не знал обязательно реализую

2022-08-03 07:21 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_9/Home_work_9_3.py
> +        for filename in filenames:
Спасибо реализую

2022-08-03 08:14 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_9/Home_work_9_1.py
> +for i in FileIter('../../README.md'):
Здесь имелось в виду до цикла сделать что-то вроде sample = re.compile('git [^а-яА-Я)"]+')
А в цикле уже: res = re.findall(sample, i, re.M | re.U)
re.compile оптимизирует шаблон поиска, чтоб re его было проще искать внутри другой строки.

2022-08-03 11:45 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_9/Home_work_9_2.py
> +    for single_date in [d for d in (start_date + dt.timedelta(n) for n in range(day_count)) if d <= end_date]:
Реализовал генератор

2022-08-04 07:41 UTC, IlyaOrlov requested changes
Всё хорошо. Оставил несколько замечаний и предложений по оптимизации.

2022-08-04 07:41 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_9/Home_work_9_3.py
> +    last_modification = dt.datetime.fromtimestamp(d_info.st_mtime)
Логика интересная. Можно и так оставить. Но достаточно было ориентироваться на время создание файла/папки, которое можно получить через os.path.getctime(путь_к_файлу)

2022-08-04 07:41 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_9/Home_work_9_3.py
> +            if check_time(f_info, 60) is True:
В стр.33 и 39: т.к. функция check_time всегда будет возвращать значение логического типа (т.е. все выходы из нее - это либо return True, либо return False), то сравнение с True можно не прописывать (обычно PyCharm это тоже подсказывает). Т.е. можно написать просто: 
```python
if check_time(f_info, 60):
```

2022-08-04 07:41 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_9/Home_work_9_2.py
> +        if single_date.timetuple().tm_wday != 5 and single_date.timetuple().tm_wday != 6:
Нехорошо, что выражение single_date.timetuple().tm_wday повторяется (и вычисляется!!!) два раза для одной и той же даты. Надо либо сохранить результат во вспомогательную переменную, либо просто сравнить так:
```python
if single_date.timetuple().tm_wday < 5:
```

2022-08-04 07:41 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_9/Home_work_9_1.py
> +    for i in FileIter('README.md'):
А стоит ли оборачивать файл в итератор, если файловый объект в Python и сам по себе является итератором? Т.е. можно написать:
```python
with open('README.md') as f:
    for i in f:
```

2022-08-04 11:25 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_9/Home_work_9_3.py
> +            if check_time(f_info, 60) is True:
спасибо, исправлю

2022-08-04 11:26 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_9/Home_work_9_2.py
> +        if single_date.timetuple().tm_wday != 5 and single_date.timetuple().tm_wday != 6:
спасибо,  исправлю

2022-08-04 11:33 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_9/Home_work_9_3.py
> +    last_modification = dt.datetime.fromtimestamp(d_info.st_mtime)
но если мы к нему обращались в течении заданного времени (что-то меняли ), то значит он нам был нужен.  Я думаю, что данный скрипт можно и в дальнейшем использовать, удалять только действительно те файлы и папки к которым давно не обращались.

2022-08-04 11:55 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_9/Home_work_9_1.py
> +    for i in FileIter('README.md'):
Думал, что  если работать с файлом итератором будет правильнее. Исправлю

2022-08-04 14:15 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_9/Home_work_9_1.py
> +    for i in FileIter('README.md'):
Это имело бы смысл, если б новый итератор привносил какой-то еще функционал (например, позволял бы читать файл не по строкам, а по параграфам).

2022-08-04 14:17 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_9/Home_work_9_3.py
> +    last_modification = dt.datetime.fromtimestamp(d_info.st_mtime)
Да, согласен. Такой подход еще называется LRU - Least Recently Used (когда в первую очередь освобождаются те ресурсы, которые использовались "наименее недавно").

2022-08-05 08:47 UTC, DNN0SHI commented
Добрый день, я исправил:
        s_pattern = re.compile(r'git [^а-яА-Я)\n"]+')
        for i in f:
            res = s_pattern.findall(i, re.M | re.U)

2022-08-05 09:47 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-08-05 09:48 UTC, merged