Ulia sherbakova
IlyaOrlov/PythonCourse2.0_June22 pull request #55
Opened 2022-07-29 19:44 UTC by uliasherb

2022-07-30 17:48 UTC, IlyaOrlov requested changes
Всё хорошо. Есть небольшое предложение по оптимизации.

2022-07-30 17:48 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz9.1.py
> +        commands += re.findall('(git [^а-яА-Я)\n"]+)', line)
Поскольку одно и то же регулярное выражение применяется к различным строкам, имеет смысл предварительно (до цикла) скомпилировать выражение, используя re.compile. Это позволит ускорить программу в целом.

2022-07-31 08:47 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz9.1.py
> +        commands += re.findall('(git [^а-яА-Я)\n"]+)', line)
добавила

2022-07-31 16:50 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz9.2.py
> +    for day in pd.bdate_range(start, end):
ОК. Только использовать pandas для такой задачки - это как стрелять из пушки по воробьям)

2022-07-31 16:55 UTC, IlyaOrlov requested changes
ОК. Есть одно небольшое замечание.

2022-07-31 16:55 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz9.4.py
> +        mas.append(h.__dict__)
Прямое обращение к приватным атрибутам объекта  практически всегда нежелательно. Чтоб объект h  красиво отрисовывался при выводе, надо у Human реализовать метод ```__repr__```.

2022-07-31 17:12 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz9.4.py
> +        mas.append(h.__dict__)
сделала

2022-08-01 06:48 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz9.4.py
> +        mas.append(h.__dict__)
Почти правильно. ```__repr__``` должен возвращать строку, а не печатать.
Печатать - удел пользователей класса Human (например, функции fun_2).

2022-08-01 06:52 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz9.4.py
> +        mas.append(h.__dict__)
поправила

2022-08-01 07:24 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-08-01 07:24 UTC, merged