Ulia Sherbakova
IlyaOrlov/PythonCourse2.0_June22 pull request #56
Opened 2022-08-01 14:55 UTC by uliasherb

2022-08-02 07:08 UTC, IlyaOrlov requested changes
Хорошо, но есть замечания.

2022-08-02 07:08 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz9.3.py
> +                shutil.rmtree(way)
Т.е. если прошло 2 минуты, мы сразу весь каталог со всем содержимым удаляем?

2022-08-02 08:15 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz9.3.py
> +                shutil.rmtree(way)
поправила

2022-08-02 09:14 UTC, IlyaOrlov requested changes
Почти правильно)

2022-08-02 09:14 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz9.3.py
> +    c = os.path.getctime(way)
Это надо проверять для каждого файла и папки! А не только для папки ".\delete"

2022-08-04 21:17 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz9.3.py
> +    c = os.path.getctime(way)
поправила

2022-08-05 09:41 UTC, IlyaOrlov requested changes
Хорошо. Только одно небольшое замечание.

2022-08-05 09:41 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.2.py
> +        p1 = multiprocessing.Process(target=big_summa, args=([1, 2, 3], [4, 5, 6]))
Всё хорошо, только в файле что-то не так с отступами (видимо, используется табуляция вместо пробела). Ну и лучше создаваемые процессы объединить в список и работать уже со списком. А то, если мы будем добавлять процессы, придется на каждый процесс делать, минимум, три изменения.

2022-08-05 12:53 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz11.2.py
> +        p1 = multiprocessing.Process(target=big_summa, args=([1, 2, 3], [4, 5, 6]))
поправила

2022-08-06 13:12 UTC, IlyaOrlov requested changes
Хорошо, но еще есть существенные замечания.

2022-08-06 13:12 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.2.py
> +        p.start()
Если мы вызываем join сразу после start, то никакого распараллеливания не получится: т.к. мы запускаем один процесс и ждём, пока он завершится вместо того, чтоб запускать новые. Надо два отдельных цикла.

2022-08-06 13:12 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.2.py
> +lst = []
А что ж lst так не повезло, что его из ```if __name__ == '__main__':``` вынесли?) Ошибки, конечно, нет, но с точки зрения дальнейшего использования lst  - нелогично.

2022-08-06 13:12 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.1.py
> +                m.start()
Если мы вызываем join сразу после start, то никакого распараллеливания не получится.

2022-08-06 13:12 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.1.py
> +    if __name__ == '__main__':
В функцию это условие тащить не нужно. Достаточно обернуть в него вызов функции fun_3.

2022-08-06 13:12 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.1.py
> +def find_primes(end, start):
Просто интересно: почему не от start до end?)

2022-08-06 13:12 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.1.py
> +    for number in range(end, start + 1):
Хорошо бы где-то в конце функции вывести итоговый список numbers.

2022-08-06 13:12 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.1.py
> +            for i in range(2, number):
Достаточно проверять числа не до number, а до квадратного корня из number.

2022-08-06 13:12 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.1.py
> +            t.join()
Если мы вызываем join сразу после start, то никакого преимущества от использования потоков не будет.

2022-08-07 13:00 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz11.2.py
> +        p.start()
поправила

2022-08-07 13:01 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz11.2.py
> +lst = []
поправила

2022-08-07 13:01 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz11.1.py
> +                m.start()
поправила

2022-08-07 13:01 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz11.1.py
> +    if __name__ == '__main__':
поправила

2022-08-07 13:02 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz11.1.py
> +def find_primes(end, start):
потому что в задании так) я скопировала оттуда название функции 
поправила

2022-08-07 13:02 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz11.1.py
> +    for number in range(end, start + 1):
поправила

2022-08-07 13:03 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz11.1.py
> +            for i in range(2, number):
поправила

2022-08-07 13:04 UTC, uliasherb commented on Practice/Ulia Sherbakova/dz11.1.py
> +            t.join()
поправила

2022-08-07 13:23 UTC, IlyaOrlov commented on Practice/Ulia Sherbakova/dz11.1.py
> +def find_primes(end, start):
И правда) Поправил)

2022-08-07 13:25 UTC, IlyaOrlov approved these changes
Всё отлично!!!

2022-08-07 13:25 UTC, merged