Chertova branch
IlyaOrlov/PythonCourse2.0_June22 pull request #58
Opened 2022-08-06 07:54 UTC by AChertova

Домашняя работа 10_3

2022-08-06 13:16 UTC, IlyaOrlov requested changes
Есть замечания по комментариям!

2022-08-06 13:16 UTC, IlyaOrlov commented on Practice/achertova/2_3pep8task.py
> +            # переименовать можно с помощью replace
Ну тут как бы сразу файл переименовывается...

2022-08-06 13:16 UTC, IlyaOrlov commented on Practice/achertova/2_3pep8task.py
>      Shuffler = shuffler()
А именование класса и экземпляра здесь нареканий не вызывают?

2022-08-06 13:16 UTC, IlyaOrlov commented on Practice/achertova/2_3pep8task.py
> +# не лучший вариант импорта
Далеко не лучший, т.к. мы тянем в свой файл все содержимое другого файла. Мало ли к каким конфликтам с нашим файлом это приведет.

2022-08-08 17:52 UTC, AChertova commented on Practice/achertova/2_3pep8task.py
> +# не лучший вариант импорта
Поняли, запомнили

2022-08-08 17:54 UTC, AChertova commented on Practice/achertova/2_3pep8task.py
> +            # переименовать можно с помощью replace
Т.е. не надо replace? Мне показалось притянуто за уши, но тогда кроме match case я ничего не нашла...

2022-08-08 17:55 UTC, AChertova commented on Practice/achertova/2_3pep8task.py
>      Shuffler = shuffler()
По экземпляру я имела ввиду в стр. 75, а класс в начале писала, поэтому не стала писать тут

2022-08-09 09:19 UTC, IlyaOrlov commented on Practice/achertova/2_3pep8task.py
>      Shuffler = shuffler()
Понято. Принято)

2022-08-09 09:20 UTC, IlyaOrlov commented on Practice/achertova/2_3pep8task.py
> +            # переименовать можно с помощью replace
Да, replace тут не подходит. Всё основное найдено.

2022-08-09 10:01 UTC, IlyaOrlov requested changes
Оставил несколько замечаний

2022-08-09 10:01 UTC, IlyaOrlov commented on Practice/achertova/Rabota11_1FindPrimea.py
> +    while start > startnew:
Странный цикл) Может, здесь просто if достаточно?

2022-08-09 12:13 UTC, AChertova commented on Practice/achertova/Rabota11_1FindPrimea.py
> +    return lst, lst1
По изначальной задумке скрипт по порядку проверял - простое ли число - делением на все предыдущие простые числа. Если да, он добавлял его в список и этот же список потом выводил. Проблема возникла, когда я поняла, что первый запрос может быть с любого числа. И как-то изящнее ничего не родилось, как вести два списка - один на печать lst1, другой делители-простые числа lst. Рассматривала вариант - удалять из единого списка числа до старта, но выбрала два списка. В первом случае вызова я возвращаю список делителей lst1 и отправляю его потом второй раз. На второй раз копятся дополнительно делители и новый список на печать. Поэтому тут мне приходится возвращать lst без лишних чисел до старта. По ощущениям, решение не оптимальное, но другого не придумалось. Потом еще подумала, что проверка деления чисел больше половины значения проверяемого числа тоже бессмысленна, тут можно время сэкономить.

2022-08-09 13:08 UTC, AChertova commented on Practice/achertova/Rabota11_1FindPrimea.py
> +    while start > startnew:
Конечно!  ヽ(°□°)ノ

2022-08-09 14:09 UTC, AChertova commented on Practice/achertova/Rabota11_2Sum.py
> +    # Если в серединке код чем-то небольшим отличается, как сделать объединение в функцию?
Хотела сначала параметры просто прописать, но вручную много не напишешь. А хотелось замерить время. Я сделала списки, чтобы последовательности нагенерировать подлиннее. Множества с моим неправильно работающим рандомом будут из 1 значения. А списки неизменяемые.  Брала, что оставалось))
Могу отдельным кодом, конечно, сделать как требуется. Но без изысков)))
Вопрос только остается - почему с процессами получается дольше?
Общее время выполнения 2 процессов: 6.687227400000211
Общее время выполнения 3 процессов: 6.3045695000000705
Общее время последовательного выполнения : 5.024641599999995
Общее время выполнения в потоках: 5.04412769999999

2022-08-10 07:07 UTC, IlyaOrlov commented on Practice/achertova/Rabota11_1FindPrimea.py
> +    return lst, lst1
Вопрос был связан немного с другим) Да, можно проверять в качестве делителей предыдущие простые числа, можно проверять делители до квадратного корня из данного числа (а не до половины) - есть разные способы. Просто список - изменяемый тип) И списки, которые меняются внутри функции check, используются и в find_primes. Поэтому возвращать их через return смысла нет.

2022-08-10 07:28 UTC, IlyaOrlov commented on Practice/achertova/Rabota11_2Sum.py
> +    # Если в серединке код чем-то небольшим отличается, как сделать объединение в функцию?
Что касается универсального кода для формирования последовательностей. Вообще функция addition как раз и должна была формировать последовательности из различных передаваемых значений (то, что делает list_maker). Операция + работает со всеми типами. Нюанс - в инициализации последовательности. Если задать lst = [] - то мы будем добавлять все в список, если lst = "" - то в строку.
Чтоб формировать последовательности входных данных, можно разные решения использовать. Например, такое: ''.join([random.choice("abcdef") for _ in range(10)]) - будет строка;
или такое: [random.randint(1, 10) for _ in range(10)] - будет список чисел.
#============
Что касается вопроса про процессы. Нужно много времени на запуск каждого процесса (в Python отдельный процесс - это фактически отдельно запущенный интерпретатор, выполняющий какую-то часть исходного скрипта). И это время может многократно превысить время на выполнение самих вычислений (как в данном случае). Таким образом, применять процессы для небольших вычислений нецелесообразно (как стрелять из пушки по воробьям). Если же вычисления занимают много времени или периодически повторяются - то можно один раз создать несколько процессов (обычно, как раз Pool для этого используется), один раз потратить на это время, и затем все поступающие задачи кидать созданным процессам. Вот в этом случае мы получим выигрыш по времени.

2022-08-10 07:29 UTC, IlyaOrlov requested changes
С кодом в целом всё ОК. Надо только разобраться с недопониманием по оставшимся вопросам.

2022-08-11 09:17 UTC, AChertova commented on Practice/achertova/Rabota11_1FindPrimea.py
> +    return lst, lst1
Поняла, да, работает

2022-08-11 18:34 UTC, IlyaOrlov requested changes
ОК. Только небольшое замечание по работе с сервером.

2022-08-11 18:34 UTC, IlyaOrlov commented on Practice/achertova/Rabota12_1Server.py
> +conn, adr = s.accept()
ОК, только сервер странный получается: рассчитан ровно на одно подключение) Прием и обработку клиентов стоит все-таки в цикле запустить. Можно в бесконечном, можно - пока клиент не пришлет какое-нибудь стоп-слово.

2022-08-16 08:36 UTC, IlyaOrlov approved these changes
Теперь - огонь!)

2022-08-16 08:36 UTC, merged