New branch shirshov
IlyaOrlov/PythonCourse2.0_June22 pull request #60
Opened 2022-08-11 08:19 UTC by DNN0SHI

Homework 11_1,2 from Lecture 11 and changing the directory structure

2022-08-11 18:29 UTC, IlyaOrlov requested changes
Есть существенные замечания. А по заданию 11.1 еще стоит ответить на теоретические вопросы (комментариями).

2022-08-11 18:29 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_11/Home_work_11_2.py
> +    return print(a + b)
Только не return print в одном выражении!

2022-08-11 18:29 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_11/Home_work_11_1.py
> +def find_primes(par):
Простые числа - это числа, которые делятся нацело только на себя: 3, 5, 7 и т.д.
Чтоб проверить, что число N простое, надо  убедиться, что ни на одно из чисел от 2 до квадратного корня из N наше число N не делится нацело (т.е. с нулевым остатком).
Ну и хорошо бы вывести на экран то, что получается в результате.

2022-08-11 19:11 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_11/Home_work_11_2.py
> +    return print(a + b)
исправлю, что то не то написал

2022-08-11 19:11 UTC, DNN0SHI commented on Practice/Shirshov_/H_W_11/Home_work_11_1.py
> +def find_primes(par):
Добрый вечер, но есть же метод "Решето Эратосфена"

2022-08-11 19:18 UTC, IlyaOrlov commented on Practice/Shirshov_/H_W_11/Home_work_11_1.py
> +def find_primes(par):
Можно и его использовать) Только я здесь итогового результата не увидел.

2022-08-12 11:13 UTC, DNN0SHI commented
Добрый день, нашел ошибки в программе, сейчас все работает корректно и метод  "Решето Эратосфена" тоже )

2022-08-12 18:29 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-08-12 18:29 UTC, merged