Stoyanov
IlyaOrlov/PythonCourse2.0_June22 pull request #61
Opened 2022-08-15 12:08 UTC by StoyanovP

hw_10

2022-08-15 19:45 UTC, IlyaOrlov requested changes
Есть некоторые замечания!

2022-08-15 19:45 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_10.py
> +new_lst = [j := int(i)**2 for i in lst if i.isdecimal() and int(i) % 5 == 0]
Здесь моржовый оператор пригодился бы, чтоб int(i) два раза не делать:
new_lst = [j**2 for i in lst if i.isdecimal() and (j := int(i)) % 5 == 0]

2022-08-15 19:45 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_10.py
> +# У меня python 3.8 поэтому не могу проверить работоспособность кода, но думаю что он должен выглядеть примерно так.
Похож) Но лучше поставить python3.10 и исправить синтаксические ошибки

2022-08-16 07:29 UTC, StoyanovP commented on Practice/Stoyanov/hw_10.py
> +new_lst = [j := int(i)**2 for i in lst if i.isdecimal() and int(i) % 5 == 0]
Поправил, все даже работает и без переменной j.

2022-08-16 07:29 UTC, StoyanovP commented on Practice/Stoyanov/hw_10.py
> +# У меня python 3.8 поэтому не могу проверить работоспособность кода, но думаю что он должен выглядеть примерно так.
У меня windows 7, и последняя версия python для него это 3.8, онлайн интерпретатор мне тоже нигде не попался на версии 3.10
Возможно ошибки в том, что после case надо перебирать константы " 'stop' | 'STOP' | 'Stop' ", а не как я сделал

2022-08-16 09:29 UTC, IlyaOrlov commented on Practice/Stoyanov/hw_10.py
> +# У меня python 3.8 поэтому не могу проверить работоспособность кода, но думаю что он должен выглядеть примерно так.
Понятно. Но на будущее.. на Win7 задерживаться не стоит) Может, это хороший повод перейти на Linux. 
Корректная версия кода должна выглядеть так:
```python
print('Этот чат бот может отвечать на такие фразы как: «Привет», «Как дела?», «Какая сегодня погода?»')
while True:
    question = input("Спрашивай! : ").lower()
    match question:
        case 'привет':
            print("Привет!")
        case 'как дела?':
            print("У меня все супер!")
        case 'какая сегодня погода?':
            print('Выгляни в окно и сам все поймешь.')
        case 'пока':
            print('Пока!')
            break
        case _:
            print("Вопрос некорректен, попробуйте сформулировать его по-другому")
```

2022-08-16 10:03 UTC, StoyanovP commented on Practice/Stoyanov/hw_10.py
> +# У меня python 3.8 поэтому не могу проверить работоспособность кода, но думаю что он должен выглядеть примерно так.
Поправил, уже несколько раз задумывался об этом))

2022-08-16 11:47 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-08-16 11:47 UTC, merged